src/authe/urls.py
from django.urls import path
from .views import register, confirm, login, logout_view

app_name = 'authe' 

urlpatterns = [
    path('register/', register, name = 'register'),
    path('confirm/<str:code>', confirm, name = 'confirm'),
    path('login/', login, name = 'login'),
    path('logout/', logout_view, name = 'logout'),
]

src/cart/urls.py
from django.urls import path
from . import views

app_name = 'cart'

urlpatterns = [
    path('', views.cart_detail, name='cart_detail'),
    path('add/<int:product_id>/', views.cart_add, name='cart_add'),
    path('remove/<int:product_id>/', views.cart_remove, name='cart_remove'),
    path('order/', views.product_cart_bot, name='order')
]

src/main/urls.py
from django.contrib import admin
from django.urls import path, include
from django.conf import settings
from django.conf.urls.static import static

urlpatterns = [
    path('admin/', admin.site.urls),
    path('cart/', include('cart.urls', namespace='cart')),
    path('', include('my_app.urls', namespace='main')),
    path('authe/', include('authe.urls'))
]

if settings.DEBUG:
    urlpatterns += static(settings.MEDIA_URL, document_root=settings.MEDIA_ROOT)

src/my_app/urls.py
from django.urls import path
from .views import product_list, product_detail, search, review_create, privacy, terms, about


app_name = 'my_app'

urlpatterns = [
    path('', product_list, name = 'product_list'),
    path('search/', search, name='search_results'),
    path('review/create/<int:product_id>', review_create, name = 'review_create'),
    path('<slug:category_slug>/', product_list, name = 'product_list_by_category'),
    path('<int:product_id>/<str:slug>', product_detail, name = 'product_detail'),
    path('privacy', privacy, name = 'privacy'),
    path('terms', terms, name = 'terms'),
    path('about', about, name = 'about')
]

src/my_app/models.py
from django.db import models
from django.urls import reverse
# Create your models here.
class Category(models.Model):
    title = models.CharField(max_length = 100, db_index = True, verbose_name = 'Заголовок')
    slug = models.SlugField(max_length=100, unique=True, default=0.0)

    class Meta:
        ordering = ('title',)
        verbose_name = 'Категория'
        verbose_name_plural = 'Категории'

    def __str__(self):
        return f"{self.title}"

    def get_absolute_url(self):
        return reverse('my_app:product_list_by_category', args=[self.slug])

class Size(models.Model):
    name = models.CharField(max_length=200, verbose_name='название', default=None)
    
    class Meta:
        verbose_name = 'Размер'
        verbose_name_plural = 'Размеры'

    def __str__(self):
        return f"{self.name}"

class Brand(models.Model):
    title = models.CharField(max_length = 100, db_index = True, verbose_name = 'Заголовок')
    slug = models.SlugField(max_length=100, unique=True, default=0.0)

    class Meta:
        ordering = ('title',)
        verbose_name = 'Бренд'
        verbose_name_plural = 'Бренды'

    def __str__(self):
        return f"{self.title}"

    def get_absolute_url(self):
        return reverse('my_app:product_list_by_brand', args=[self.slug])

class Product(models.Model):
    category = models.ForeignKey(Category, related_name='product', on_delete=models.CASCADE)
    brand = models.ForeignKey(Brand, related_name='product', on_delete=models.CASCADE)
    title = models.TextField(max_length=100, db_index=True, verbose_name='Заголовок')
    slug = models.SlugField(max_length=100, db_index=True, unique=True, default=0.0)
    image = models.ImageField(upload_to='images', blank=True)
    body = models.TextField(max_length=1000, blank=True, verbose_name='Описание')
    price = models.DecimalField(max_digits=100, decimal_places=1, default=0.0, verbose_name='Цена')
    available = models.BooleanField(default=True)
    created = models.DateField(auto_now_add=True)
    uploaded = models.DateField(auto_now=True)
    size = models.ManyToManyField(Size, max_length=20, verbose_name = 'размер')
    
    class Meta:
        ordering = ('title',)
        verbose_name = 'Продукт'
        verbose_name_plural = 'Продукты'
        index_together = (('id', 'slug'),)

    def __str__(self):
        return f"{self.title}"

    def get_absolute_url(self):
        return reverse('my_app:product_detail', args=[self.id, self.slug])

class Review(models.Model):
    product = models.ForeignKey(Product, related_name='product', on_delete=models.CASCADE, blank=True, null=True)
    customer_name = models.CharField(max_length=300, verbose_name='Имя')
    description = models.TextField(max_length = 1000, verbose_name='Описание')
    phone_number = models.CharField(max_length=12, verbose_name='Номер телефона')
    created = models.DateTimeField(auto_now_add=True)  

    def __str__(self):
        return f"{self.customer_name}"
    class Meta:
        verbose_name = 'Отзыв'
        verbose_name_plural = 'Отзывы'

src/my_app/forms.py
from .models import Product, Review
from django.forms import ModelForm, TextInput, Textarea
from django import forms

class ReviewForm(forms.ModelForm):
    customer_name = forms.CharField(max_length=30, required=False)
    description = forms.CharField(max_length=300, required=False)

    class Meta:
        model = Review
        fields = ('customer_name', 'description')

src/my_app/views/product.py
from my_app.models import Product, Category, Review
from django.shortcuts import render, get_object_or_404
from cart.forms import CartAddProductForm
from rest_framework import filters

def product_list(request, category_slug=None):
    category = None
    categories = Category.objects.all()
    products = Product.objects.filter(available=True)
    
    if category_slug:
        category = get_object_or_404(Category, slug=category_slug)
        products = products.filter(category=category)
    return render(request, 'product.html', 
                {
                    'category':category,
                    'categories':categories, 
                    'products':products
                })

def product_detail(request, product_id, slug):
    product = get_object_or_404(Product, id=product_id, slug=slug, available=True)
    cart_product_form = CartAddProductForm()
    review = Review.objects.filter(product_id = product_id)
    reviews = Review.objects.all()
    return render(request, 'category.html', 
                {
                    'product': product, 
                    'cart_product_form':cart_product_form, 
                    'review': review, 
                    'reviews':reviews
                })


def search(request):
    title = str(request.GET['q'])
    products = Product.objects.filter(title__icontains=title)
    return render(request, 'product.html', {'products':products})

def privacy(request):
    return render(request, 'privacy.html') 

def terms(request):
    return render(request, 'terms.html') 

def about(request):
    return render(request, 'about.html') 

src/my_app/views/review.py
from django.shortcuts import render, redirect
from my_app.forms import ReviewForm
from my_app.models import Review, Product

def review_create(request, product_id):
    error = ''
    if request.user.is_authenticated:
        if request.method == 'POST':
            form = ReviewForm(request.POST)
            if form.is_valid():
                description = request.POST['description']
                Review.objects.create(description=description, customer_name=request.user.username, product_id=product_id)
                return render(request, 'product.html')
            else:
                error = 'Форма была неверной'

        form = ReviewForm()
        context = {
            'form': form,
            'error': error
        }
        return render(request, 'review_create.html', context)
    return redirect( 'authe:login')

src/my_app/templates/about.html
{% extends "base.html" %}
{% block content %}
<br>
<br>
<br>
<br>
<h1>About US</h1>
<img src="https://hips.hearstapps.com/hmg-prod.s3.amazonaws.com/images/index-1603982718.png?crop=1.00xw:1.00xh;0,0&resize=1200:*" class="img-fluid" alt="...">
<br>
<br>
<div class="card">
    <div class="card-header">
        CONCEPT
    </div>
    <div class="card-body">
      <h5 class="card-title">Music, screens, projections, modern graphics, fashion, colors...</h5>
      <p class="card-text">Bershka stores stand out in the world with their strategic location and well-detailed architecture. The stores determine the fashion with their showcases, which are the windows of the products offered inside. Bershka selects the best trade centers and locations in each city and is located in major shopping centers. Detached buildings are preferred and Bershka architectural studio designs are studied according to the brand's image and philosophy.</p>
    </div>
</div>
<br>
<img src="https://static.bershka.net/4/static/itxwebstandard/images/test/company/company05.jpg?20210605032525" class="rounded float-start" alt="...">
<img src="https://static.bershka.net/4/static/itxwebstandard/images/test/company/company06.jpg?20210605032525" class="rounded float-end" alt="...">
<br>
<br>
<br>
<br>
<br>
<br>
<br>
<br>
<br>
<br>
<br>
<br>
<br>
<br>
<br>
<div class="row">
    <div class="col-sm-6">
      <div class="card">
        <div class="card-body">
          <h5 class="card-title">OUR PRODUCTS</h5>
          <h3 class="card-title">BSK is the brand of young people. Therefore, the products are always geared towards the needs and interests of young people.</h3>
          <p class="card-text">Products belonging to different lines under Bershka are presented in different areas in stores. In each section, Bershka, BSK&Man products are classified and presented according to their styles. The stores have all kinds of products, from casual wear to sportswear and from basics to the latest trends of the season.</p>
        </div>
      </div>
    </div>
    <div class="col-sm-6">
      <div class="card">
        <div class="card-body">
          <h5 class="card-title">BRAND</h5>
          <h3 class="card-title">BRAND</h3>
          <p class="card-text">Bershka describes itself as a brand focused on increasing demand. In just 2 years, it strengthens its brand image in 100 stores. Currently, the 18-year-old chain of stores has more than 1,000 stores in more than 70 markets, with sales representing 9% of total revenue across the group. Bershkan's target audience is adventurous young people who follow the latest trends in music, social media and new technologies.</p>
        </div>
      </div>
    </div>
</div>
<br>
<br>
<div class="card mb-3">
    <img src="https://abruzzoworld.com/wp-content/uploads/2021/03/social-holding.jpg" class="card-img-top" alt="...">
    <div class="card-body">
      <h5 class="card-title">Growth and expansion through integrated channels</h5>
      <p class="card-text">H&M Group is expanding online, with a focus on omnichannel sales. Our customers want to be able to shop and be inspired when and how they chose – in our stores, on our brands’ own websites, on digital marketplaces and in social media.</p>
      <p class="card-text"><small class="text-muted">Panama is scheduled to open in the second half of 2021 via franchise.</small></p>
    </div>
  </div>
<br>
<br>
{% endblock %}

src/my_app/templates/base.html
{% load static %}
<!DOCTYPE html>
<html>
<head>
  <meta charset="utf-8" />
  <meta name="viewport" content="width=device-width, initial-scale=1.0">
  <meta http-equiv="X-UA-Compatible" content="ie=edge">
  <title>{% block title %}Мой магазин{% endblock %}</title>
  <link rel="stylesheet" href="{% static 'css/base.css' %}" >
  <link rel="stylesheet" href="https://cdnjs.cloudflare.com/ajax/libs/font-awesome/4.7.0/css/font-awesome.min.css">
  <script src="{% static 'js/static.js'%}"></script>
  <link href="https://cdn.jsdelivr.net/npm/bootstrap@5.0.0-beta1/dist/css/bootstrap.min.css" rel="stylesheet" integrity="sha384-giJF6kkoqNQ00vy+HMDP7azOuL0xtbfIcaT9wjKHr8RbDVddVHyTfAAsrekwKmP1" crossorigin="anonymous">
  <script src="https://code.jquery.com/jquery-3.2.1.slim.min.js" integrity="sha384-KJ3o2DKtIkvYIK3UENzmM7KCkRr/rE9/Qpg6aAZGJwFDMVNA/GpGFF93hXpG5KkN" crossorigin="anonymous"></script>
  <script src="https://cdnjs.cloudflare.com/ajax/libs/popper.js/1.12.9/umd/popper.min.js" integrity="sha384-ApNbgh9B+Y1QKtv3Rn7W3mgPxhU9K/ScQsAP7hUibX39j7fakFPskvXusvfa0b4Q" crossorigin="anonymous"></script>
  <script src="https://maxcdn.bootstrapcdn.com/bootstrap/4.0.0/js/bootstrap.min.js" integrity="sha384-JZR6Spejh4U02d8jOt6vLEHfe/JQGiRRSQQxSfFWpi1MquVdAyjUar5+76PVCmYl" crossorigin="anonymous"></script>
  <link rel="stylesheet" href="https://maxcdn.bootstrapcdn.com/font-awesome/4.7.0/css/font-awesome.min.css">
  <script src="https://code.jquery.com/jquery-3.3.1.js"></script>
  <link href="https://cdn.jsdelivr.net/npm/bootstrap@5.0.0-beta3/dist/css/bootstrap.min.css" rel="stylesheet" integrity="sha384-eOJMYsd53ii+scO/bJGFsiCZc+5NDVN2yr8+0RDqr0Ql0h+rP48ckxlpbzKgwra6" crossorigin="anonymous">
  <script src="https://cdn.jsdelivr.net/npm/bootstrap@5.0.0-beta3/dist/js/bootstrap.bundle.min.js" integrity="sha384-JEW9xMcG8R+pH31jmWH6WWP0WintQrMb4s7ZOdauHnUtxwoG2vI5DkLtS3qm9Ekf" crossorigin="anonymous"></script>
  <script src="https://cdn.jsdelivr.net/npm/@popperjs/core@2.9.1/dist/umd/popper.min.js" integrity="sha384-SR1sx49pcuLnqZUnnPwx6FCym0wLsk5JZuNx2bPPENzswTNFaQU1RDvt3wT4gWFG" crossorigin="anonymous"></script>
  <script src="https://cdn.jsdelivr.net/npm/bootstrap@5.0.0-beta3/dist/js/bootstrap.min.js" integrity="sha384-j0CNLUeiqtyaRmlzUHCPZ+Gy5fQu0dQ6eZ/xAww941Ai1SxSY+0EQqNXNE6DZiVc" crossorigin="anonymous"></script>
  <script src="https://cdnjs.cloudflare.com/ajax/libs/jquery/3.2.1/jquery.min.js"></script>
  <script src="https://cdnjs.cloudflare.com/ajax/libs/twitter-bootstrap/4.1.3/js/bootstrap.bundle.min.js"></script>
</head>
<body>
  <div class="wrapper">
    <header>
      <nav>
        <div class="logo">
          <a class='logo' href="/">HOME</a>
        </div>
        <div class="menu">
          <ul>
            <li><a href="{% url 'cart:cart_detail' %}">CART</a></li>
            <li><a href="{% url 'authe:login'%}">LOGIN</a></li>
            <li><a href="{% url 'authe:register'%}">SIGNIN</a></li>
            <li><a href="{% url 'authe:logout'%}">LOGOUT</a></li>
            <li>
              <form action="{% url 'my_app:search_results' %}" method="get" class="box">
                <input class="topnav" name="q" type="text" placeholder="Search...">
              </form>
            </li>
            </div>
          </ul>
        </div>
      </nav> 
    </header>
    <div id="content">
      {% block content %}{% endblock %}
    </div>
  </div>
<style>
  .box{
    width: 300px;
    vertical-align: middle;
    white-space: nowrap;
    position: relative;
  }

  .topnav{
    width: 300px;
    height: 50px;
    background: #e7dede;
    border: none;
    font-size: 13pt;
    color: #63717f;
    padding-left: 45px;
    -webkit-border-radius: 5px;
    -moz-border-radius: 5px;
    border-radius: 5px;
  }
  
  .footer-basic {
  padding:40px 0;
  background-color:#e7dede;
  color:#4b4c4d;
  }

  .footer-basic ul {
    padding:0;
    list-style:none;
    text-align:center;
    font-size:18px;
    line-height:1.6;
    margin-bottom:0;
  }

  .footer-basic li {
    padding:0 10px;
  }

  .footer-basic ul a {
    color:inherit;
    text-decoration:none;
    opacity:0.8;
  }

  .footer-basic ul a:hover {
    opacity:1;
  }

  .footer-basic .social {
    text-align:center;
    padding-bottom:25px;
  }

  .footer-basic .social > a {
    font-size:24px;
    width:40px;
    height:40px;
    line-height:40px;
    display:inline-block;
    text-align:center;
    border-radius:50%;
    border:1px solid #ccc;
    margin:0 8px;
    color:inherit;
    opacity:0.75;
  }

  .footer-basic .social > a:hover {
    opacity:0.9;
  }

  .footer-basic .copyright {
    margin-top:15px;
    text-align:center;
    font-size:13px;
    color:#aaa;
    margin-bottom:0;
  }

  body {
    background-color: rgb(255, 255, 255);
    text-align: center;
  }
  
  .icon-button {
    background-color: rgb(255, 255, 255);
    border-radius: 3.6rem;
    cursor: pointer;
    display: inline-block;
    font-size: 2.0rem;
    height: 3.6rem;
    line-height: 3.6rem;
    margin: 0 5px;
    position: relative;
    text-align: center;
    -webkit-user-select: none;
      -moz-user-select: none;
        -ms-user-select: none;
            user-select: none;
    width: 3.6rem;
  }

  /* Circle */
  .icon-button span {
    border-radius: 0;
    display: block;
    height: 0;
    left: 50%;
    margin: 0;
    position: absolute;
    top: 50%;
    -webkit-transition: all 0.3s;
      -moz-transition: all 0.3s;
        -o-transition: all 0.3s;
            transition: all 0.3s;
    width: 0;
  }
  .icon-button:hover span {
    width: 3.6rem;
    height: 3.6rem;
    border-radius: 3.6rem;
    margin: -1.8rem;
  }
  .twitter span {
    color: #3B5998;
    background-color: #4099ff;
  }
  .facebook span {
    color: #4099ff;
    background-color: #3B5998;
  }
  .google-plus span {
    color: rgb(241, 82, 9);
    background: radial-gradient(circle at 30% 107%, #fdf497 0%, #fdf497 5%, #fd5949 45%,#d6249f 60%,#285AEB 90%);
  }

  /* Icons */
  .icon-button i {
    background: none;
    color: white;
    height: 3.6rem;
    left: 0;
    line-height: 3.6rem;
    position: absolute;
    top: 0;
    -webkit-transition: all 0.3s;
      -moz-transition: all 0.3s;
        -o-transition: all 0.3s;
            transition: all 0.3s;
    width: 3.6rem;
    z-index: 10;
  }
  .icon-button .icon-twitter {
    color: #4099ff;
  }
  .icon-button .icon-facebook {
    color: #3B5998;
  }
  .icon-button .icon-google-plus {
    color: #db5a3c;
  }
  .icon-button:hover .icon-twitter,
  .icon-button:hover .icon-facebook,
  .icon-button:hover .icon-google-plus {
    color: white;
  }
  span{
    color: rgb(201, 182, 182);

  }
</style>
<div class="footer-basic">
  <footer> 
    <a href="https://telegram.me/asserubot" class="icon-button twitter"><i class="icon-twitter"></i><span>T</span></a>
    <a href="https://facebook.com" class="icon-button facebook"><i class="icon-facebook"></i><span>F</span></a>
    <a href="https://www.instagram.com/derbisheva_a/" class="icon-button google-plus"><i class="icon-google-plus"></i><span>I</span></a>
    <br>
    <br>
    <ul class="list-inline">
      <li class="list-inline-item"><a href="/">Home</a></li>
      <li class="list-inline-item"><a href="{% url 'my_app:product_list' %}">Category</a></li>
      <li class="list-inline-item"><a href="{% url 'my_app:about' %}">About</a></li>
      <li class="list-inline-item"><a href="{% url 'my_app:terms' %}">Terms</a></li>
      <li class="list-inline-item"><a href="{% url 'my_app:privacy' %}">Privacy Policy</a></li>
    </ul>
    <ul class="list-inline">
      <li class="list-inline-item"><a href="https://www.massimodutti.com/us/">Massimo Dutti</a></li>
      <li class="list-inline-item"><a href="https://www.zara.com/ww/">Zara</a></li>
      <li class="list-inline-item"><a href="https://www.stradivarius.com/ww/">Stradivarious</a></li>
      <li class="list-inline-item"><a href="https://www.pullandbear.com/">Pull&Bear</a></li>
      <li class="list-inline-item"><a href="https://www.bershka.com/">Bershka</a></li>
      <li class="list-inline-item"><a href="https://www.oysho.com/ru/">Oysho</a></li>
      <li class="list-inline-item"><a href="https://shop.mango.com/us">Mango</a></li>
      <li class="list-inline-item"><a href="https://www2.hm.com/en_us/index.html">H&M</a></li>
    </ul>
    <p class="copyright">ASERU SHOP © 2018</p>
  </footer>
</div>
</body>
</html>

src/my_app/templates/category.html
{% extends "base.html" %}
{% load static %}
{% block title %}
{{ product.name }}
{% endblock %}
{% block content %}
<br>
<br>
<br>
<br>
<div class="product-detail">
    <img src="{% if product.image %}{{ product.image.url }}{% else %}
    {% static 'img/no_image.png' %}{% endif %}">
    <h1>{{ product.title }}</h1>
    <h2>
        <a href="{{ product.category.get_absolute_url }}">{{product.category }}</a>
    </h2>
    <h2>
        {{product.brand }}
    </h2>
    <p class="price">${{ product.price }}</p>
    <form action="{% url 'cart:cart_add' product.id %}" method="POST">
        {{ cart_product_form }}
        {% csrf_token %}
        <input type='submit' value='в корзину'>
    </form>

{{ product.body|linebreaks }}
<br>
<br>
<br>
<br>
<br>
<br>
<br>
<br>
<br>
<br>
<br>
<br>
<br>
<br>
<br>
<br>
<br>
<h3>Отзывы</h3>
<br>
{% for review in reviews %}
<div class="card">
    <div class="card-header">
        <h4>{{ review.customer_name }}</h4>
    </div>
    <div class="card-body">
      <blockquote class="blockquote mb-0">
        <p>{{ review.description }}</p>
        <footer class="blockquote-footer">{{ review.created }}</footer>
      </blockquote>
    </div>
</div>
{% endfor %}
<br>
<button type="button" class="btn btn-outline-secondary"><a href="{% url 'my_app:review_create' product.id %}" method="POST">Оставить отзыв</a></button>
<br>
<br>
</div>
{% endblock %}

src/my_app/templates/product.html
{% extends "base.html" %}
{% load static %}
{% block title %}
{% if category %}{{ category.title }}{% else %}Товары{% endif %}
{% endblock %}
{% block content %}
<br>
<br>
<br>
<br>
<div id="carouselExampleIndicators" class="carousel slide" data-ride="carousel">
    <ol class="carousel-indicators">
      <li data-target="#carouselExampleIndicators" data-slide-to="0" class="active"></li>
      <li data-target="#carouselExampleIndicators" data-slide-to="1"></li>
      <li data-target="#carouselExampleIndicators" data-slide-to="2"></li>
    </ol>
    <div class="carousel-inner">
      <div class="carousel-item active">
        <img class="d-block w-100" src="https://jetexcdn.sfo2.cdn.digitaloceanspaces.com/jetex.com/wp-content/uploads/2020/02/Paris-Fashion-Week-scaled.jpg" alt="First slide">
      </div>
      <div class="carousel-item">
        <img class="d-block w-100" src="https://i.ytimg.com/vi/BZ3DCJfJSXU/maxresdefault.jpg" alt="Second slide">
      </div>
      <div class="carousel-item">
        <img class="d-block w-100" src="https://fashionmagazine.com/wp-content/uploads/2020/02/2020-02-11-1.jpg" alt="Third slide">
      </div>
    </div>
    <a class="carousel-control-prev" href="#carouselExampleIndicators" role="button" data-slide="prev">
      <span class="carousel-control-prev-icon" aria-hidden="true"></span>
      <span class="sr-only">Previous</span>
    </a>
    <a class="carousel-control-next" href="#carouselExampleIndicators" role="button" data-slide="next">
      <span class="carousel-control-next-icon" aria-hidden="true"></span>
      <span class="sr-only">Next</span>
    </a>
</div>
<div id="sidebar">
    <h3>Категория</h3>
    <ul>
        <li {% if not category %}class="selected"{% endif %}>
            <a href="{% url 'my_app:product_list' %}">Все</a>
        </li>
        {% for c in categories %}
        <li {% if category.slug == c.slug %}class="selected" {% endif %}>
            <a href="{{ c.get_absolute_url }}">{{ c.title }}</a>
        </li>
        {% endfor %}
    </ul>
</div>
<br>
<div id="main" class="product-list">
    <h1>{% if category %}{{ category.title }}{% else %}Товар{% endif %}</h1>
    {% for product in products %}
    <div class="item">
        <a href="{{ product.get_absolute_url }}">
            <img src="{% if product.image %}{{ product.image.url }}{%else %}{% static 'img/no_image.png' %}{% endif %}">
        </a>
        <a href="{{ product.get_absolute_url }}">{{ product.title }}</a>
        <br>
        ${{ product.price }}
    </div>
    {% endfor %}
</div>
{% endblock %}

src/my_app/templates/review_create.html
{% extends 'base.html'%}
{% block content %}
<html lang="en">
<head>
    <meta charset="UTF-8">
    <meta name="viewport" content="width=device-width, initial-scale=1.0">
    <title>Review</title>
</head>
<body>
    <style>
        /* Bordered form */
    .form {
        border: 400px solid #ffffff;
        border-top: 400px;
        border-bottom: 400px;
        margin: 100px;
    }
      
      /* Full-width inputs */
    input[type=text], input[type=password] {
        width: 100%;
        padding: 12px 20px;
        margin: 8px 0;
        display: inline-block;
        border: 1px solid #ccc;
        box-sizing: border-box;
    }
    </style>
    <form class="form" method = 'POST'>
        {% csrf_token %}
        {{form.as_p}} 
        <button class="btn btn-outline-success my-2 my-sm-0" type="submit">SUBMIT</button>
    </form>
</body>
</html>
{% endblock %}

src/my_app/templates/search_results.html
{% extends "base.html" %}
{% block content %}
<ul>
    {% for products in products %}
      <li>
        {{ product.title }}, {{ product.body }}
      </li>
    {% endfor %}
  </ul>
{% endblock %}